#!/bin/bash

################################################################################
# Usage:
#   mythrokumake
#   mythrokumake install
#   mythrokumake remove
#
# This is a simple wrapper script that does two things:
#   - Avoids the need to add an entry in your ~/.bashrc file for the
#     ROKU_DEV_TARGET environment variable.
#   - Allows you to specify multiple Roku targets if needed.
################################################################################

export ROKU_DEV_TARGET=192.168.1.20; make $*
export ROKU_DEV_TARGET=192.168.1.21; make $*
export ROKU_DEV_TARGET=192.168.1.22; make $*

